THREADS: 48
SAMPLE: [
         "WT_SPO11oligos_Rep1"
#         "WT_SPO11oligos_Rep2",
#         "WT_SPO11oligos_Rep3"
        ]
MAPPING:
      mode: "both"
      reference: "data/index/TAIR10_chr_all"
COVERAGE:
      regionBodyLength: 2000
      startLabel: "TSS"
      endLabel: "TTS"
      upstream: 2000
      downstream: 2000
      flankName: "2kb"
      binSize: 10
      binName: "10bp"
      sortRegions: "keep"
