THREADS: 48
SAMPLE: [
         "WT_SPO11oligos_Rep1"
#         "WT_SPO11oligos_Rep2",
#         "WT_SPO11oligos_Rep3"
        ]
FEATURES:
      chrName: [
#                "Chr1_Chr2_Chr3_Chr4_Chr5",
                "Chr1",
                "Chr2",
                "Chr3",
                "Chr4",
                "Chr5"
               ]
MAPPING:
      mode: "both"
      reference: "data/index/TAIR10_chr_all"
COVERAGE:
      regionBodyLength: 500
      startLabel: "Start"
      endLabel: "End"
      upstream: 2000
      downstream: 2000
      flankName: "2kb"
      binSize: 10
      binName: "10bp"
      sortRegions: "keep"
